name = "chumbada-minha-selecao"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "CART"
class_name = "CartSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CartSession"]
